name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-conventional-commits-naming:
    runs-on: ubuntu-latest
    steps:
      - name: check-conventional-commits-naming
        id: check-conventional-commits-naming
        uses: agenthunt/conventional-commit-checker-action@v2.0.1